name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linters (placeholder for future steps)
        run: echo "This will be the Run linters step"

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration

      - name: Run end-to-end tests
        run: npm run test:e2e

      - name: Perform static code analysis (placeholder for future steps)
        run: echo "This will be the Perform static code analysis step"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hello_devops:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Save Docker image as tarball
        run: |
          docker save ${{ secrets.DOCKER_HUB_USERNAME }}/hello_devops:latest > hello_devops.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: hello_devops.tar

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image from artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image

      - name: Load Docker image from tarball
        run: |
          docker load < hello_devops.tar

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hello_devops:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Deploy to AWS (placeholder for future steps)
        run: echo "This will be the AWS deployment step"
